language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  include:
    - php: 5.4
      env: dependencies=lowest

sudo: false

dist: trusty

before_script:
  - composer self-update
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then composer require satooshi/php-coveralls -n ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '5.6' ]]; then composer self-update --snapshot && composer install -n ; fi
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;

script:
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then phpunit --coverage-clover clover.xml ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '5.6' ]]; then phpunit ; fi
  - vendor/bin/athletic --path tests/Benchmark --formatter GroupedFormatter
after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then php vendor/bin/coveralls -v ; fi
